### ISSUE TITLE
Too Many Open Files?

### ISSUE THREAD

**Issue by sdthomas69** [cormorack/yodapy#26]
```
[########################################] | 100% Completed |  8.1stornado.application - ERROR - Multiple exceptions in yield list
Traceback (most recent call last):
  File "/anaconda3/envs/yodapy/lib/python3.6/site-packages/tornado/gen.py", line 849, in callback
    result_list.append(f.result())
  File "/anaconda3/envs/yodapy/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/anaconda3/envs/yodapy/lib/python3.6/site-packages/distributed/deploy/local.py", line 183, in _start_worker
    yield w._start()
  File "/anaconda3/envs/yodapy/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/anaconda3/envs/yodapy/lib/python3.6/site-packages/tornado/gen.py", line 315, in wrapper
    yielded = next(result)
  File "/anaconda3/envs/yodapy/lib/python3.6/site-packages/distributed/nanny.py", line 142, in _start
    listen_args=self.listen_args)
  File "/anaconda3/envs/yodapy/lib/python3.6/site-packages/distributed/core.py", line 236, in listen
    self.listener.start()
  File "/anaconda3/envs/yodapy/lib/python3.6/site-packages/distributed/comm/tcp.py", line 376, in start
    backlog=backlog)
  File "/anaconda3/envs/yodapy/lib/python3.6/site-packages/tornado/netutil.py", line 134, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/anaconda3/envs/yodapy/lib/python3.6/socket.py", line 144, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 24] Too many open files
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-10-61cc7c21f268> in <module>()
----> 1 dataset_list = ooi.request_data(begin_date, end_date).to_xarray()

~/Documents/workspace/OceanDataAccess/yodapy/yodapy/datasources/ooi/ooi_m2m.py in to_xarray(self, **kwargs)
    276         if self._data_type == 'netCDF':
    277             dataset_list = []
--> 278             client = Client()
    279             futures = client.map(lambda durl: check_data_status(
    280                 self._session, durl

/anaconda3/envs/yodapy/lib/python3.6/site-packages/distributed/client.py in __init__(self, address, loop, timeout, set_as_default, scheduler_file, security, asynchronous, name, heartbeat_interval, **kwargs)
    576                                      io_loop=self.loop)
    577 
--> 578         self.start(timeout=timeout)
    579 
    580         from distributed.recreate_exceptions import ReplayExceptionClient

/anaconda3/envs/yodapy/lib/python3.6/site-packages/distributed/client.py in start(self, **kwargs)
    696             self._started = self._start(**kwargs)
    697         else:
--> 698             sync(self.loop, self._start, **kwargs)
    699 
    700     def __await__(self):

/anaconda3/envs/yodapy/lib/python3.6/site-packages/distributed/utils.py in sync(loop, func, *args, **kwargs)
    251             e.wait(10)
    252     if error[0]:
--> 253         six.reraise(*error[0])
    254     else:
    255         return result[0]

/anaconda3/envs/yodapy/lib/python3.6/site-packages/six.py in reraise(tp, value, tb)
    691             if value.__traceback__ is not tb:
    692                 raise value.with_traceback(tb)
--> 693             raise value
    694         finally:
    695             value = None

/anaconda3/envs/yodapy/lib/python3.6/site-packages/distributed/utils.py in f()
    236             yield gen.moment
    237             thread_state.asynchronous = True
--> 238             result[0] = yield make_coro()
    239         except Exception as exc:
    240             error[0] = sys.exc_info()

/anaconda3/envs/yodapy/lib/python3.6/site-packages/tornado/gen.py in run(self)
   1097 
   1098                     try:
-> 1099                         value = future.result()
   1100                     except Exception:
   1101                         self.had_exception = True

/anaconda3/envs/yodapy/lib/python3.6/site-packages/tornado/gen.py in run(self)
   1105                     if exc_info is not None:
   1106                         try:
-> 1107                             yielded = self.gen.throw(*exc_info)
   1108                         finally:
   1109                             # Break up a reference to itself

/anaconda3/envs/yodapy/lib/python3.6/site-packages/distributed/client.py in _start(self, timeout, **kwargs)
    753                 self.cluster = LocalCluster(loop=self.loop, asynchronous=True,
    754                                             **self._startup_kwargs)
--> 755                 yield self.cluster
    756             except (OSError, socket.error) as e:
    757                 if e.errno != errno.EADDRINUSE:

/anaconda3/envs/yodapy/lib/python3.6/site-packages/tornado/gen.py in run(self)
   1097 
   1098                     try:
-> 1099                         value = future.result()
   1100                     except Exception:
   1101                         self.had_exception = True

/anaconda3/envs/yodapy/lib/python3.6/asyncio/tasks.py in _wrap_awaitable(awaitable)
    535     that will later be wrapped in a Task by ensure_future().
    536     """
--> 537     return (yield from awaitable.__await__())
    538 
    539 

/anaconda3/envs/yodapy/lib/python3.6/site-packages/tornado/gen.py in run(self)
   1105                     if exc_info is not None:
   1106                         try:
-> 1107                             yielded = self.gen.throw(*exc_info)
   1108                         finally:
   1109                             # Break up a reference to itself

/anaconda3/envs/yodapy/lib/python3.6/site-packages/distributed/deploy/local.py in _start(self, ip, n_workers)
    164         self.scheduler.start(scheduler_address)
    165 
--> 166         yield [self._start_worker(**self.worker_kwargs) for i in range(n_workers)]
    167 
    168         self.status = 'running'

/anaconda3/envs/yodapy/lib/python3.6/site-packages/tornado/gen.py in run(self)
   1097 
   1098                     try:
-> 1099                         value = future.result()
   1100                     except Exception:
   1101                         self.had_exception = True

/anaconda3/envs/yodapy/lib/python3.6/site-packages/tornado/gen.py in callback(f)
    847             for f in children:
    848                 try:
--> 849                     result_list.append(f.result())
    850                 except Exception as e:
    851                     if future.done():

/anaconda3/envs/yodapy/lib/python3.6/site-packages/tornado/gen.py in run(self)
   1105                     if exc_info is not None:
   1106                         try:
-> 1107                             yielded = self.gen.throw(*exc_info)
   1108                         finally:
   1109                             # Break up a reference to itself

/anaconda3/envs/yodapy/lib/python3.6/site-packages/distributed/deploy/local.py in _start_worker(self, death_timeout, **kwargs)
    181               death_timeout=death_timeout,
    182               silence_logs=self.silence_logs, **kwargs)
--> 183         yield w._start()
    184 
    185         self.workers.append(w)

/anaconda3/envs/yodapy/lib/python3.6/site-packages/tornado/gen.py in run(self)
   1097 
   1098                     try:
-> 1099                         value = future.result()
   1100                     except Exception:
   1101                         self.had_exception = True

/anaconda3/envs/yodapy/lib/python3.6/site-packages/tornado/gen.py in run(self)
   1105                     if exc_info is not None:
   1106                         try:
-> 1107                             yielded = self.gen.throw(*exc_info)
   1108                         finally:
   1109                             # Break up a reference to itself

/anaconda3/envs/yodapy/lib/python3.6/site-packages/distributed/nanny.py in _start(self, addr_or_port)
    154 
    155         logger.info('        Start Nanny at: %r', self.address)
--> 156         response = yield self.instantiate()
    157         if response == 'running':
    158             assert self.worker_address

/anaconda3/envs/yodapy/lib/python3.6/site-packages/tornado/gen.py in run(self)
   1097 
   1098                     try:
-> 1099                         value = future.result()
   1100                     except Exception:
   1101                         self.had_exception = True

/anaconda3/envs/yodapy/lib/python3.6/site-packages/tornado/gen.py in run(self)
   1105                     if exc_info is not None:
   1106                         try:
-> 1107                             yielded = self.gen.throw(*exc_info)
   1108                         finally:
   1109                             # Break up a reference to itself

/anaconda3/envs/yodapy/lib/python3.6/site-packages/distributed/nanny.py in instantiate(self, comm)
    222                 result = yield gen.with_timeout(
    223                         timedelta(seconds=self.death_timeout),
--> 224                         self.process.start()
    225                 )
    226             except gen.TimeoutError:

/anaconda3/envs/yodapy/lib/python3.6/site-packages/tornado/gen.py in run(self)
   1097 
   1098                     try:
-> 1099                         value = future.result()
   1100                     except Exception:
   1101                         self.had_exception = True

/anaconda3/envs/yodapy/lib/python3.6/site-packages/tornado/gen.py in wrapper(*args, **kwargs)
    313                 try:
    314                     orig_stack_contexts = stack_context._state.contexts
--> 315                     yielded = next(result)
    316                     if stack_context._state.contexts is not orig_stack_contexts:
    317                         yielded = _create_future()

/anaconda3/envs/yodapy/lib/python3.6/site-packages/distributed/nanny.py in start(self)
    357                         init_result_q=self.init_result_q,
    358                         child_stop_q=self.child_stop_q,
--> 359                         uid=uid),
    360         )
    361         self.process.daemon = True

/anaconda3/envs/yodapy/lib/python3.6/site-packages/distributed/process.py in __init__(self, loop, target, name, args, kwargs)
     71         # (for example due to SIGKILL). This variable is otherwise unused except
     72         # for the assignment here.
---> 73         parent_alive_pipe, self._keep_child_alive = mp_context.Pipe(duplex=False)
     74 
     75         self._process = mp_context.Process(target=self._run, name=name,

/anaconda3/envs/yodapy/lib/python3.6/multiprocessing/context.py in Pipe(self, duplex)
     60         '''Returns two connection object connected by a pipe'''
     61         from .connection import Pipe
---> 62         return Pipe(duplex)
     63 
     64     def Lock(self):

/anaconda3/envs/yodapy/lib/python3.6/multiprocessing/connection.py in Pipe(duplex)
    510             c2 = Connection(s2.detach())
    511         else:
--> 512             fd1, fd2 = os.pipe()
    513             c1 = Connection(fd1, writable=False)
    514             c2 = Connection(fd2, readable=False)

OSError: [Errno 24] Too many open files
```

**Comment by lsetiawan** [comment]
I tried this with my MacOSX:
OS Version: 10.13.4

I was able to get the data without the error above, not sure what's going on here.

**Comment by sdthomas69** [comment]
That does seem odd; maybe there’s something off with my machine.  I’m running 10.13.5.  Any chance you can upgrade and try with the latest version?

-Shawn

**Comment by lsetiawan** [comment]
I have updated my MacOSX to version 10.13.5, and I am still able to run the commands successfully. Thanks.

**Comment by amanda-tan** [comment]
Seems to me like this is a dask problem. The files keep opening but not terminated. Might be worth a reboot of the machine.

**Comment by lsetiawan** [comment]
Not using dask anymore to request data. Closing.
